
clear; clc; close all;

x = linspace(0, 2*pi, 200);
y = sin(x);

fancy_plot(x, y, 'linear', true, true);  % new figure, finalize legend

%%

clear; clc; close all;

x = linspace(0, 2*pi, 200);
y = sin(x);

fancy_plot(x, y, 'linear', true, true, struct( ...
    'legend_label', '$\sin(x)$', ...
    'x_label', '$\theta$', ...
    'y_label', '$\log(\sin(\theta))$', ...
    'marker_type', '--s', ...
    'marker_div', 50, ...
    'color', [0.4940, 0.1840, 0.5560], ...
    'font_name', 'Times New Roman', ...
    'x_lim', [-0.2, 2*pi+0.2], ...
    'y_lim', [-1.2, 1.2], ...
    'x_ticks', 0:pi/2:2*pi, ...
    'x_ticklabels', {{'$0$','$\frac{\pi}{2}$','$\pi$','$\frac{3\pi}{2}$','$2\pi$'}}, ...
    'legend_location', 'southeast', ...
    'legend_box', 'off' ...
));


%%


clear; clc; close all;

x = linspace(0, 2*pi, 200);
y1 = sin(x);
y2 = cos(x);

fancy_plot(x, y1, 'linear', true, false);
fancy_plot(x, y2, 'linear', false, true);


%%

clear; clc; close all;

x = linspace(0, 2*pi, 200);
y1 = sin(x);
y2 = cos(x);
y3 = tan(x);

% Common custom settings
x_ticks = 0:pi/2:2*pi;
x_ticklabels = {{'$0$', '$\frac{\pi}{2}$', '$\pi$', '$\frac{3\pi}{2}$', '$2\pi$'}};
y_ticks = -1:0.5:1;
y_ticklabels = {{'$-1$', '$-0.5$', '$0$', '$0.5$', '$1$'}};

% Struct for sin(x)
s1 = struct( ...
    'legend_label', '$\sin(\theta)$', ...
    'x_label', '$\theta$', ...
    'y_label', '$f(\theta)$', ...
    'color', [0, 0.4470, 0.7410], ...
    'marker_type', '--o', ...
    'marker_div', 20, ...
    'font_name', 'Serif', ...
    'font_size', 50, ...
    'font_size_legend', 35, ...
    'x_lim', [-2, 2*pi+2], ...
    'y_lim', [-1.1, 1.1], ...
    'x_ticks', x_ticks, ...
    'x_ticklabels', x_ticklabels, ...
    'y_ticks', y_ticks, ...
    'y_ticklabels', y_ticklabels, ...
    'legend_location', 'southwest', ...
    'legend_box', 'on' ...
);

% Struct for cos(x)
s2 = struct( ...
    'legend_label', '$\cos(\theta)$', ...
    'x_label', '$\theta$', ...
    'y_label', '$f(\theta)$', ...
    'color', [0.8500, 0.3250, 0.0980], ...
    'marker_type', ':^', ...
    'marker_div', 20, ...
    'font_name', 'Serif', ...
    'font_size', 50, ...
    'font_size_legend', 35, ...
    'x_lim', [0, 2*pi], ...
    'y_lim', [-1.1, 1.1], ...
    'x_ticks', x_ticks, ...
    'x_ticklabels', x_ticklabels, ...
    'y_ticks', y_ticks, ...
    'y_ticklabels', y_ticklabels, ...
    'legend_location', 'southwest', ...
    'legend_box', 'on' ...
);

s3 = struct( ...
    'legend_label', '$\tan(\theta)$', ...
    'x_label', '$\theta$', ...
    'y_label', '$f(\theta)$', ...
    'color', [9, 121, 105]./255, ...
    'marker_type', '-*', ...
    'marker_div', 20, ...
    'font_name', 'Serif', ...
    'font_size', 50, ...
    'font_size_legend', 35, ...
    'x_lim', [-1, 2*pi], ...
    'y_lim', [-1.1, 1.1], ...
    'x_ticks', x_ticks, ...
    'x_ticklabels', x_ticklabels, ...
    'y_ticks', y_ticks, ...
    'y_ticklabels', y_ticklabels, ...
    'legend_location', 'southwest', ...
    'legend_box', 'on' ...
);

% Plot sin(x)
fancy_plot(x, y1, 'linear', true, false, s1);

% Plot cos(x)
fancy_plot(x, y2, 'linear', false, false, s2);

fancy_plot(x, y3, 'linear', false, true, s3);


%%