clear; clc; close all;

% Data
x = linspace(-pi, pi, 500);
y = exp(-x) .* sin(2 * x);

% Custom settings
custom = struct( ...
    'x_label', '$t/\tau_g$', ...
    'y_label', '$e^{-x} \sin(2x)$', ...
    'legend_label', '$y(t)$', ...
    'legend_location', 'northeast',...
    'font_size', 60, ...
    'font_size_legend', 40, ...
    'line_width', 3, ...
    'marker_size', 18, ...
    'marker_type', 'd-', ...             % diamond markers + solid line
    'font_name', 'Helvetica', ...
    'marker_div', 50, ...
    'x_lim', [-pi-0.5, pi+0.5], ...
    'y_lim', [-5, 15], ...
    'x_ticks', [-pi, 0, pi], ...
    'x_ticklabels', ["$-\pi$", "$0$", "$\pi$"],...  % <-- string array!
    'y_ticks', [0, 10, 15], ...
    'y_ticklabels', ["0", "10", "15"]...  % <-- string array!
);

% Call the plot function
fancy_plot_old(x, y, 'linear', custom);
